# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"3\n\x14ImageClassifierInput\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"&\n\x15ImageClassifierOutput\x12\r\n\x05label\x18\x01 \x01(\t2_\n\x0fImageClassifier\x12L\n\x07Predict\x12\x1f.inference.ImageClassifierInput\x1a .inference.ImageClassifierOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGECLASSIFIERINPUT']._serialized_start=30
  _globals['_IMAGECLASSIFIERINPUT']._serialized_end=81
  _globals['_IMAGECLASSIFIEROUTPUT']._serialized_start=83
  _globals['_IMAGECLASSIFIEROUTPUT']._serialized_end=121
  _globals['_IMAGECLASSIFIER']._serialized_start=123
  _globals['_IMAGECLASSIFIER']._serialized_end=218
# @@protoc_insertion_point(module_scope)
